config/routes.rb
MyForum::Engine.routes.draw do
  root 'welcome#index'

  match 'signin', to: 'users#signin', via: [:get, :post]
  match 'logout', to: 'users#logout', via: [:get]
  match 'forgot_password',  to: 'users#forgot_password',    via: [:get, :post]

  match 'unread_topics',    to: 'forums#unread_topics',     via: [:get],    as: :unread_topics
  match 'mark_all_as_read', to: 'forums#mark_all_as_read',  via: [:get],    as: :mark_all_as_read

  match 'post/:id',         to: 'posts#show',               via: [:get],    as: :post_content
  match 'post/preview',     to: 'posts#preview',            via: [:post],   as: :post_preview

  resources :images
  resources :avatars
  resources :attachments

  resources :users do
    patch :avatar_update

    collection do
      get :autocomplete
    end
  end

  resources :private_messages

  resources :forums, only: [:index, :show] do
    resources :topics do
      patch :pin
      patch :close
      patch :delete
      resources :posts
    end
  end

  namespace :admin do
    root 'dashboard#index'

    match 'forums', to: 'forums#index', via: [:get]
    match 'mail_list', to: 'mail#index', via: [:get, :post]

    resources :emoticons
    resources :users
    resources :roles
    resources :categories do
      resources :forums
    end
  end
end

app/models/my_forum/role.rb
module MyForum
  class Role < ActiveRecord::Base
    has_many :user_roles
    has_many :users, through: :user_roles
  end
end

app/controllers/my_forum/admin/roles_controller.rb
require_dependency "my_forum/application_controller"

module MyForum
  class Admin::RolesController < ApplicationController

    before_filter :verify_admin

    layout 'layouts/my_forum/admin_application'

    def index
      @roles = Role.all
    end

    def new
      @role = Role.new
    end

    def create
      @role = Role.new(role_params)
      @role.save
      redirect_to admin_roles_path
    end

    def edit

    end

    def update

    end

    private

    def role_params
      params.require(:role).permit(:name, :color)
    end
  end
end

app/helpers/my_forum/admin/roles_helper.rb
module MyForum
  module Admin::RolesHelper
  end
end

app/views/my_forum/admin/roles/index.haml
.page-header
  %h2= t('.roles')

.pull-right=link_to t('.create-role'), new_admin_role_path, class: 'btn btn-primary btn-sm'

- if @roles.blank?
  =t('.no-roles')
- else
  %table
    - @roles.each do |role|
      %tr
        %td= role.name

app/views/my_forum/admin/roles/new.haml
.page-header
  %h2= t('.new-role')

= form_for @role, url: admin_roles_path do |f|
  .row
    = f.text_field :name, placeholder: t('.role_name')
  .row
    = f.text_field :color

  -# .row
  -#   admin access
  -#   .btn-group{ 'data-toggle' => "buttons" }
  -#     =f.label :admin_access, class: 'btn btn-success btn-sm active' do
  -#       = f.radio_button :admin_access, true
  -#       yes
  -#     =f.label :admin_access, class: 'btn btn-danger btn-sm' do
  -#       = f.radio_button :admin_access, false
  -#       &nbsp;no&nbsp;



  = f.submit