config/routes.rb
MyForum::Engine.routes.draw do
  root 'welcome#index'

  match 'signin', to: 'users#signin', via: [:get, :post]
  match 'logout', to: 'users#logout', via: [:get]
  match 'forgot_password',  to: 'users#forgot_password',    via: [:get, :post]

  match 'unread_topics',    to: 'forums#unread_topics',     via: [:get],    as: :unread_topics
  match 'mark_all_as_read', to: 'forums#mark_all_as_read',  via: [:get],    as: :mark_all_as_read

  match 'post/:id',         to: 'posts#show',               via: [:get],    as: :post_content
  match 'post/preview',     to: 'posts#preview',            via: [:post],   as: :post_preview

  resources :images
  resources :avatars
  resources :attachments

  resources :users do
    patch :avatar_update

    collection do
      get :autocomplete
    end
  end

  resources :private_messages

  resources :forums, only: [:index, :show] do
    resources :topics do
      patch :pin
      patch :close
      patch :delete
      resources :posts
    end
  end

  namespace :admin do
    root 'dashboard#index'

    match 'forums', to: 'forums#index', via: [:get]
    match 'mail_list', to: 'mail#index', via: [:get, :post]

    resources :emoticons
    resources :users
    resources :roles
    resources :categories do
      resources :forums
    end
  end
end

app/models/my_forum/forum.rb
module MyForum
  class Forum < ActiveRecord::Base
    belongs_to :category
    has_many  :topics
    has_many  :posts

    def has_unread_posts?(current_user)
      return false unless current_user

      latest_post_ids = self.topics.where('latest_post_created_at >= ?', current_user.created_at).pluck(:latest_post_id)
      read_log = []
      read_log = LogReadMark.where("user_id = ? AND post_id IN (?)", current_user.id, latest_post_ids).pluck(:post_id) unless latest_post_ids.blank?

      !(latest_post_ids - read_log).empty?
    end

    # Forum index page
    def topics_with_latest_post_info(page: 0, per_page: 30)
      Topic.paginate_by_sql("
        SELECT
          my_forum_topics.*,
          my_forum_topics.latest_post_created_at AS last_post_time,
          my_forum_topics.latest_post_login AS last_post_user_login
        FROM my_forum_topics
        WHERE my_forum_topics.forum_id = #{self.id} AND my_forum_topics.deleted IS FALSE
        ORDER BY my_forum_topics.pinned DESC, my_forum_topics.latest_post_created_at DESC
      ", page: page, per_page: per_page)
    end

    def self.unread_topics_with_latest_post_info(user_id:, page: 0, per_page: 30)
      log_topic_ids = LogReadMark.where(user_id: user_id).pluck(:topic_id)
      log_topic_ids = [0] if log_topic_ids.empty?

      Topic.paginate_by_sql("
        SELECT
          my_forum_topics.*,
          my_forum_topics.latest_post_created_at AS last_post_time,
          my_forum_topics.latest_post_login AS last_post_user_login
        FROM my_forum_topics
        WHERE my_forum_topics.id NOT IN (#{log_topic_ids.join(',')}) AND my_forum_topics.deleted IS FALSE
        ORDER BY my_forum_topics.id DESC
      ", page: page, per_page: per_page)
    end

    def unread_topics_with_user
      log_topic_ids = LogReadMark.where(user_id: current_user.id).pluck(:topic_id)
      Topic.where('id NOT IN (?)', log_topic_ids).order('updated_at DESC').paginate(:page => params[:page], :per_page => 30)
    end
  end
end

app/controllers/my_forum/admin/forums_controller.rb
require_dependency "my_forum/application_controller"

module MyForum
  class Admin::ForumsController < ApplicationController

    before_filter :verify_admin

    layout 'layouts/my_forum/admin_application'

    before_filter :find_category, only: [ :new, :create ]

    def index
      @categories = Category.all
    end

    def new
      @forum = @forum_category.forums.build
    end

    def create
      @forum = @forum_category.forums.build(forum_params)
      @forum.save ? redirect_to(admin_forums_path) : raise('forum not created')
    end

    protected

    def find_category
      @forum_category = Category.find(params[:category_id])
    end

    def forum_params
      params.require(:forum).permit(:name, :description)
    end
  end
end

app/controllers/my_forum/forums_controller.rb
require_dependency "my_forum/application_controller"

module MyForum
  class ForumsController < ApplicationController
    before_filter :find_forum, only: [:show]

    def show
      check_access_permissions(@forum)
      @forum_topics = @forum.topics_with_latest_post_info(page: params[:page], per_page: Post::PER_PAGE)
    end

    def unread_topics
      redirect_to root_path and return unless current_user
      @forum_topics = Forum.unread_topics_with_latest_post_info(user_id: current_user_id, page: params[:page], per_page: 30)

      render action: :show
    end

    def mark_all_as_read
      redirect_to root_path and return unless current_user

      Topic.find_in_batches(batch_size: 500) do |topic_group|
        topic_group.each do |topic|
          log = LogReadMark.find_or_create_by(user_id: current_user.id, topic_id: topic.id)
          log.post_id = topic.latest_post_id
          log.save
        end
      end

      redirect_to root_path
    end

    private

    def find_forum
      @forum = Forum.find(params[:id])
    end
  end
end

app/helpers/my_forum/admin/forums_helper.rb
module MyForum
  module Admin::ForumsHelper
  end
end

app/helpers/my_forum/forums_helper.rb
module MyForum
  module ForumsHelper

    def forum_status_img(forum)
      unread  = 'lada_logo_unread.jpg'
      read    = 'lada_logo.jpg'

      display_as = read
      display_as = unread if forum.has_unread_posts?(current_user)

      image_tag(display_as, width: '66px')
    end

    def forum_name(forum)
      html  = content_tag :strong, link_to(forum.name, forum_path(forum))
      html += content_tag :div, forum.description
      html.html_safe
    end

    def forum_stat(forum)
      html  = content_tag(:div, t('.topics_count', topics_count: forum.topics_count))
      html += content_tag(:div, t('.messages_count', messages_count: forum.posts_count))
      html.html_safe
    end

    def forum_last_message_info(forum)
      topic = forum.topics.order('latest_post_created_at DESC').first

      html  = content_tag(:div, topic ? (t('.last_answer_from') + topic.latest_post_login) : '-' )
      html += content_tag(:div, topic ? (link_to((t('.in_forum') + topic.name), forum_topic_path(topic.forum_id, topic.id))) : '-' )
      html += content_tag(:div, topic ? forum_time(topic.latest_post_created_at) : '-' )

      html.html_safe
    end

    def new_topic_button
      return unless current_user
      return unless @forum
      content_tag :div, class: 'buttons_for_new_topic' do
        link_to t('my_forum.create_new_topic'), new_forum_topic_path(@forum), class: 'btn btn-primary'
      end
    end
  end
end

app/views/my_forum/admin/forums/index.haml
.page-header
  %h2= t('.forums')

= link_to t('.create_category'), new_admin_category_path, class: 'btn btn-primary btn-sm'



.container-fluid
  - @categories.each do |category|
    .row.category_box
      .col-md-10.category_name
        =category.name
      .col-md-2.category_name
        .pull-right.btn-group.btn-group-sm{ rel: 'group' }
          = link_to t('.create_forum'), new_admin_category_forum_path(category), class: 'btn btn-default'
        .pull-right.btn-group.btn-group-sm{ rel: 'group' }
          = link_to t('.edit'), edit_admin_category_path(category), class: 'btn btn-default'

        -# .btn-group.btn-group-sm
        -#   %button{ class: 'btn btn-default dropdown-toggle', data: { toggle: 'dropdown', aria_haspopup: true, aria_expanded: false } }
        -#     Options
        -#     %span.caret
        -#   %ul{ class: 'dropdown-menu'}
        -#     %li= link_to t('.edit'), edit_admin_category_path(category)
        -#     %li= link_to t('.delete'), '#'









      .row.category_forums
        .col-md-12
          = t('.no_forums') if category.forums.blank?
          -category.forums.each do |forum|
            .row
              .col-md-12
                %strong=forum.name
                %br
                =forum.description

                .pull-right
                  =link_to '', '#', class: 'glyphicon glyphicon-edit'
                  =link_to '', '#', class: 'glyphicon glyphicon-trash'

app/views/my_forum/admin/forums/new.haml
%h2= t('.create_new_forum')

= form_for @forum, url: admin_category_forums_path do |f|
  = f.text_field :name, placeholder: t('.forum_name')
  = f.text_field :description, placeholder: t('.forum_description')
  = f.submit